[tool.black]
line-length = 120
target-version = ['py37']

[tool.isort]
profile = "black"
known_local_folder = ["domain", "generated", "infrastructure", "presentation"]
skip_glob = "generated/*"
line_length = 120
