name: BuildImageAndTestWebapp

on:
  - pull_request
  - push

jobs:
  build-image-and-test-webapp:
    name: Build docker image and test webapp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare for running local apiserver
        run: pip3 install -r stub_api_server/requirements.txt

      - name: Run local apiserver
        run: RESPONSE_FILE_PATH="stub_api_server/mesh_5x5.json" FLASK_ENV=development FLASK_APP=stub_api_server flask run --host=0.0.0.0 --port=9050 &

      - name: Generate API client
        run: ./generate_client.sh

      - name: Build image
        run: docker build . -t sla_dashboard

      - name: Run webapp against local apiserver
        run: |
          docker run \
            --name sla_dashboard \
            --rm \
            --add-host host.docker.internal:host-gateway \
            -e KTAPI_URL="host.docker.internal:9050" \
            -e KTAPI_AUTH_EMAIL="dummy" \
            -e KTAPI_AUTH_TOKEN="dummy" \
            -v "$(pwd)/data:/app/data" \
            -p 8050:8050 \
            -d \
            sla_dashboard:latest

      - name: Warm-up time
        run: sleep 5

      - name: Inspect webapp
        run: docker logs sla_dashboard

      - name: Test webapp - Index
        run: curl --fail --include 127.0.0.1:8050/

      - name: Test webapp - Matrix
        run: curl --fail --include 127.0.0.1:8050/matrix

      - name: Test webapp - Time Series
        run: curl --fail --include 127.0.0.1:8050/time-series?from=646&to=733

      - name: Stop webapp
        run: docker stop sla_dashboard

      - name: Stop local apiserver
        run: curl 127.0.0.1:9050/shutdown
